language: c
    
before_install:
    - sudo apt-get update
    - sudo apt-get install gcc-multilib
    - sudo apt-get install lynx
    - sudo apt-get install lib32stdc++6

before_script:
    - SMPATTERN="http:.*sourcemod-.*-linux.*"
    - SMURL="http://www.sourcemod.net/smdrop/1.8/"
    - SMPACKAGE=`lynx -dump "$SMURL" | egrep -o "$SMPATTERN" | tail -1`
    - SMFILE=$(wget ${SMPACKAGE} -q -O -)
    - wget "${SMURL}${SMFILE}"
    - tar -xzf $SMFILE
    - wget https://github.com/ErikMinekus/sm-ripext/releases/download/1.0.3/sm-ripext-1.0.3-linux.tar.gz
    - tar -xzf sm-ripext-1.0.3-linux.tar.gz
    - cp ts-mover.sp addons/sourcemod/scripting/
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - chmod +x compile.sh

script: 
    - ./compile.sh

after_script:
    - ls ../plugin